{{- $gpuCount := .Values.gpuCount -}}
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ .Values.servingName }}
  namespace: {{ .Values.namespace }}
spec:
  predictors:
    - graph:
        implementation: {{ .Values.implementation }}
        modelUri: {{ .Values.modelUri }}
        name: inference
      name: default
      replicas: {{ .Values.replicas }}
      labels:
        servingName: "{{ .Values.servingName }}"
        serviceName: "{{ .Values.servingName }}"
        servingType: seldon-serving
        servingVersion: "{{ .Values.servingVersion }}"