kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arena:{{ .Release.Namespace }}:{{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - deployments
    - nodes
    - nodes/*
    - services/proxy
    - persistentvolumes
    verbs:
    - get
    - list
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - list
{{- with .Values.clusterRoles }}
{{- toYaml . | nindent 2 }}
{{- end }}
