{{- if (ne (len .Values.ports) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorrt-inference-server.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorrt-inference-server.chart" . }}
    app: {{ template "tensorrt-inference-server.name" . }}
    servingName: {{ .Values.servingName }}
    servingType: "trt-serving"
    servingVersion: "{{ .Values.servingVersion }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- range $portKey,$portVal := .Values.ports }}
    - name: {{ $portKey }}
      port: {{ $portVal }}
      targetPort: {{ $portVal }}
    {{- end }}
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorrt-inference-server.name" . }}
{{- end }}
