{{- if and (eq .Values.modelServiceExists false) (ne (len .Values.ports) 0) }}
apiVersion: v1
kind: Service
metadata:
  {{ if eq .Values.enableIstio true }}
  name:  {{ .Values.servingName }}
  {{ else }}
  name: {{ template "tensorflow-serving.fullname" . }}
  {{ end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
    servingName: {{ .Values.servingName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- range $portKey,$portVal := .Values.ports }}
    - name: {{ $portKey }}
      port: {{ $portVal }}
      targetPort: {{ $portVal }}
    {{- end }}
  selector:
    {{ if eq .Values.enableIstio true }}
    app: {{ template "tensorflow-serving.name" . }}
    serviceName: "{{ .Values.servingName }}"
    {{ else }}
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorflow-serving.name" . }}
    {{ end }}
{{- end }}
